services:

  spark:
    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: spark-delta-engine

    volumes:
      - ./spark:/app/spark
      - ./datasets:/app/datasets
      - ./configs:/app/configs
      - ./logs:/app/logs
      - ./tests:/app/tests
      - ./dashboard:/app/dashboard

    working_dir: /app

    stdin_open: true
    tty: true

    command: tail -f /dev/null

    env_file:
      - .env

    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}

    restart: unless-stopped


  streamlit-dashboard:

    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: streamlit-dashboard

    command: >
      streamlit run dashboard/app.py
      --server.port 8501
      --server.address 0.0.0.0

    ports:
      - "8501:8501"

    volumes:
      - ./dashboard:/app/dashboard
      - ./configs:/app/configs
      - ./logs:/app/logs

    working_dir: /app

    env_file:
      - .env

    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}

    restart: unless-stopped