name: Digital Payment Pipeline CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      # -----------------------------------
      # 1. Checkout code
      # -----------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      # -----------------------------------
      # 2. Configure AWS credentials
      # -----------------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # -----------------------------------
      # 3. Login to Amazon ECR
      # -----------------------------------
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # -----------------------------------
      # 4. Build Docker image
      # -----------------------------------
      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .

      # -----------------------------------
      # 5. Tag Docker image
      # -----------------------------------
      - name: Tag Docker Image
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY

          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_URI:$IMAGE_TAG

          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV

      # -----------------------------------
      # 6. Push image to ECR
      # -----------------------------------
      - name: Push Image to ECR
        run: |
          docker push $ECR_URI:$IMAGE_TAG

      # -----------------------------------
      # 7. Deploy Spark Container & Trigger Airflow DAG
      # -----------------------------------
      - name: Deploy to EC2 and Trigger Pipeline
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            set -e

            ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
            REGION=${{ secrets.AWS_REGION }}
            REPO=${{ secrets.ECR_REPOSITORY }}
            IMAGE_TAG=${{ github.sha }}

            IMAGE="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO:$IMAGE_TAG"

            echo "==========================================="
            echo "Navigating to project directory..."
            echo "==========================================="

            cd ~/spark-cluster/digital-payments-platform

            echo "==========================================="
            echo "Pulling latest GitHub code..."
            echo "==========================================="

            git pull origin main

            echo "==========================================="
            echo "Logging into Amazon ECR..."
            echo "==========================================="

            aws ecr get-login-password --region $REGION \
            | docker login --username AWS --password-stdin \
            $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

            echo "==========================================="
            echo "Pulling latest Spark image..."
            echo "==========================================="

            docker pull $IMAGE

            echo "==========================================="
            echo "Stopping old Spark container..."
            echo "==========================================="

            docker stop spark-delta-engine || true
            docker rm spark-delta-engine || true

            echo "==========================================="
            echo "Starting updated Spark container..."
            echo "==========================================="

            docker run -d \
              --name spark-delta-engine \
              --network host \
              --env-file .env \
              -v $(pwd)/spark:/app/spark \
              -v $(pwd)/datasets:/app/datasets \
              -v $(pwd)/configs:/app/configs \
              -v $(pwd)/logs:/app/logs \
              -v $(pwd)/tests:/app/tests \
              -w /app \
              $IMAGE \
              tail -f /dev/null

            echo "==========================================="
            echo "Waiting for Spark container..."
            echo "==========================================="

            sleep 20

            echo "==========================================="
            echo "Checking running containers..."
            echo "==========================================="

            docker ps

            echo "==========================================="
            echo "Triggering Airflow DAG..."
            echo "==========================================="

            docker exec airflow-webserver \
            airflow dags trigger digital_payments_pipeline

            echo "==========================================="
            echo "Deployment completed successfully"
            echo "==========================================="